blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('cms.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/urls.py
from django.urls import path
import cms.views as cms_view

urlpatterns = [
    path('signup/', cms_view.Signup, name='signup'),
    path('', cms_view.PostIndex.as_view(), name='blogposts'),
    path('tag/<str:slug>/', cms_view.TagIndexView.as_view(), name='tagged'),
    path('dashboard/', cms_view.UserPostList.as_view(), name='dashboard'),
    path('create/',  cms_view.BlogPostCreate.as_view(), name="create"),
    path('<int:pk>/', cms_view.BlogPostDetail.as_view(), name='detail'),
]

cms/models.py
from django.db import models as models
from django.db.models import CharField, ImageField, TextField
from django.conf import settings
from taggit.managers import TaggableManager


class BlogPost(models.Model):

    # Fields
    page_title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="upload/images/")
    content = models.TextField()
    meta_title = models.CharField(max_length=60)
    meta_description = models.CharField(max_length=160)
    category = models.CharField(max_length=30)
    location = models.CharField(max_length=30)

    # Relationship Fields
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, related_name="blogposts",
    )

    tags = TaggableManager()

    class Meta:
        ordering = ('-pk',)

cms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

cms/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView, CreateView
from cms.forms import SignUpForm
from taggit.models import Tag
from cms.models import BlogPost


def Signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('dashboard')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context


class PostIndex(TagMixin, ListView):
    template_name = 'cms/index.html'
    model = BlogPost
    paginate_by = '10'
    queryset = BlogPost.objects.all()
    context_object_name = 'blogposts'


class TagIndexView(TagMixin, ListView):
    template_name = 'cms/index.html'
    model = BlogPost
    paginate_by = '10'
    context_object_name = 'blogposts'

    def get_queryset(self):
        return BlogPost.objects.filter(tags__slug=self.kwargs.get('slug'))


class UserPostList(LoginRequiredMixin, ListView):
    model = BlogPost
    template_name = 'cms/dashboard.html'
    context_object_name = 'all_posts_by_user'

    def get_queryset(self):
        return BlogPost.objects.filter(author=self.request.user)


class BlogPostCreate(LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = '__all__'
    success_url = '/dashboard'


class BlogPostDetail(DetailView):
    model = BlogPost

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Whatshot in the City.</title>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="{% static 'cms/css/cms_main.css' %}" rel="stylesheet"/>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,700i" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container ">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'blogposts' %}">WHATSHOT</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                           <li class="dropdown">
                              <a href="#" class="dropdown-toggle text-uppercase" data-toggle="dropdown"><strong>{{ user.username }}</strong><b class="caret"></b></a>
                              <ul class="dropdown-menu">
				  <li><a href="{% url 'blogposts' %}">WEBSITE</a></li>
				  <li><a href="{% url 'dashboard' %}">DASHBOARD</a></li>
				  <li><a href="{% url 'create' %}">NEW POST</a></li>
                                  <li><a href="{% url 'logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>
                        {% else %}
                          <li><a href="{% url 'login' %}"><strong>LOGIN</strong></a></li>  
			  <li><a href="{% url 'signup' %}"><strong>SIGN UP</strong></a></li>
	              {% endif %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>

        <div class="container">
	  {% block content %}
	  {% endblock %}
        </div>
	
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        </body>
    </html>

blog/templates/cms/blogpost_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <img class="banner-img" alt="banner" src="{{ MEDIA_URL }}{{ blogpost.image.url }}"/>
  <h1 class="text-center text-capitalize post-title">{{ blogpost.page_title }}</h1>
</div>
<div class="row">
  <p class="post-text text-justify">
    {{ blogpost.content }}
  </p>
</div>
<div class="row info-row">
  <span class="text-uppercase btn btn-default">{{ blogpost.category }}</span>
  <span class="text-uppercase pull-right btn btn-default">{{ blogpost.location }}</span>
</div>
{% endblock %}

blog/templates/cms/blogpost_form.html
{% extends 'base.html' %}

{% block title %}Create New Post{% endblock %}

{% block content %}
<h1 class="text-center">CREATE NEW BLOG POST</h2>
<div class="form-container">
  <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="form-group">
      <label for="id_page_title">Page title:</label>
      <input type="text" class="form-control" name="page_title" maxlength="50" required="" id="id_page_title">
    </div>
    <div class="form-group">
      <label for="id_image">Image:</label>
      <input type="file" class="form-control" name="image" accept="image/*" required="" id="id_image">
    </div>
    <div class="form-group">
      <label for="id_content">Content:</label>
      <textarea name="content" class="form-control" cols="40" rows="10" required="" id="id_content"></textarea>
    </div>
    <div class="form-group">
      <label for="id_meta_title">Meta title:</label>
      <input type="text"  class="form-control" name="meta_title" maxlength="60" required="" id="id_meta_title">
    </div>
    <div class="form-group">
      <label for="id_meta_description">Meta description:</label>
      <input type="text" class="form-control" name="meta_description" maxlength="160" required="" id="id_meta_description">
    </div>
    <div class="form-group">
      <label for="id_category">Category:</label>
      <input type="text" class="form-control" name="category" maxlength="30" required="" id="id_category">
    </div>
    <div class="form-group">
      <label for="id_location">Location:</label>
      <input type="text" class="form-control" name="location" maxlength="30" required="" id="id_location">
    </div>
    <div class="form-group">
      <input name="author" class="form-control" type="hidden" value="{{ user.id }}" id="id_author"/>
    </div>
    <div class="form-group">
      <label for="id_tags">Tags:</label>
      <input type="text" class="form-control" name="tags" required="" id="id_tags"> <span class="helptext">A comma-separated list of tags.</span>
    </div>
    <input type="submit" class="btn btn-primary form-btn" value="Save" />
  </form>
</div>
{% endblock %}

blog/templates/cms/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  {% if all_posts_by_user %}
     <table class="table">
       <thead>
	 <tr>
	   <th>POST TITLE</th>
	   <th>BANNER IMAGE</th>
	   <th>CATEGORY</th>
	   <th>LOCATION</th>
	 </tr>
       </thead>
       <tbody>
	 {% for each in all_posts_by_user %}
	 <tr>
	   <th>{{ each.page_title }}</th>
	   <th><img alt="blogImage" height="40" src="{{ MEDIA_URL }}{{ each.image.url }}"/></th>
	   <th>{{ each.category }}</th>
	   <th>{{ each.location }}</th>
	 </tr>
	 {% endfor %}
       </tbody>
     </table>
     {% else %}
     <div class="jumbotron">
       <h2 class="text-center text-capitalize">welcome <span class="dash-user">"{{ user.username }}" </span>you have not made any post.</h2>
     </div>
     {% endif %}
{% endblock %}

blog/templates/cms/index.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}
     <div class="container">
       <a class="btn btn-default btn-lg tag-btn" href="{% url 'blogposts' %}">Home</a>
     {% for tag in tags %}
       <a class="btn btn-default btn-lg tag-btn" href="{% url 'tagged' tag.slug %}">{{ tag.name }}
       </a>
       {% empty %}
       <h3>No Tags<h3>
     {% endfor %}
   </div>
     {% for each in blogposts %}
     <a class="card-link" href="{% url 'blogposts' %}{{ each.pk }}">
      <div class="card col-sm-12 col-md-3">
        <img alt="blogImage" src="{{ MEDIA_URL }}{{ each.image.url }}" height="150">
	<div class="card-container">
	  <p class="text-center text-uppercase"><strong>{{ each.page_title }}</strong></p>
	  <p class="text-justify">{{ each.content|truncatechars:120 }}<a href="{{ each.pk }}"><strong>READ MORE</strong></a></p>
	  <span class="text-uppercase">{{ each.category }}</span>
	  <span class="text-uppercase pull-right">{{ each.location }}</span>
	</div>
      </div>
      </a>
   {% endfor %}
{% endblock %}